name: Remove Version (Pro Beta)
run-name: Remove Version (Pro Beta) ${{ inputs.tag_name }}

on:
  workflow_dispatch:
    inputs:
      tag_name:
        type: string
        description: "Which tag are you using? (ex: v1.0.0+0)"
        required: true
      is_pr:
        type: boolean
        description: "Whether to create a pr to the microsoft/winget-pkgs? (default to false)"
        default: false
        required: false

jobs:
  get_version:
    name: Get version
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version_step.outputs.version }}
      release: ${{ steps.version_step.outputs.release }}
    steps:
      - name: Set version
        id: version_step
        run: |
          RELEASE=$(echo "$TAG_NAME" | sed -e "s/v//")
          echo "release: $RELEASE"

          VERSION=$(echo "$TAG_NAME" | sed -e "s/v//" -e "s/+/./")
          echo "version: $VERSION"

          echo "release=$RELEASE" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        env:
          TAG_NAME: ${{ inputs.tag_name }}

  commit:
    needs:
      - get_version
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/winget-pkgs
          sparse-checkout: |
            manifests/i/PicGuard
            .gitattributes
            .gitignore
          token: ${{ secrets.WINGET_UPDATER_TOKEN }}

      - name: Pull & Push
        run: |
          git remote add upstream https://github.com/microsoft/winget-pkgs
          echo "::group::pull"
          git pull upstream master
          echo "::endgroup::"
          git push

      - name: Create branch
        run: |
          git branch Remove-PicGuard.PicGuard.Pro.Beta-${{ needs.get_version.outputs.version }}
          git switch Remove-PicGuard.PicGuard.Pro.Beta-${{ needs.get_version.outputs.version }}

      - name: Remove version
        run: rm -rf manifests/i/PicGuard/PicGuard/Pro/Beta/${{ needs.get_version.outputs.version }}

      - name: Commit & Push
        run: |
          git config --global user.email "${{ vars.GIT_EMAIL }}"
          git config --global user.name "${{ vars.GIT_NAME }}"
          git config --global core.autocrlf false
          git add .
          git commit -m "Remove version: PicGuard.PicGuard.Pro.Beta version ${{ needs.get_version.outputs.version }}"
          git push --set-upstream origin Remove-PicGuard.PicGuard.Pro.Beta-${{ needs.get_version.outputs.version }}

  pr:
    if: ${{ inputs.is_pr }}
    needs:
      - get_version
      - commit
    runs-on: ubuntu-22.04
    environment:
      name: Deploy-Pull-Request-Pro-Removed-Beta
    steps:
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.WINGET_UPDATER_TOKEN }}
        run: |
          gh pr create \
            --repo https://github.com/microsoft/winget-pkgs \
            --base master \
            --head ${{ github.repository_owner }}:Remove-PicGuard.PicGuard.Pro.Beta-${{ needs.get_version.outputs.version }} \
            --title "Remove version: PicGuard.PicGuard.Pro.Beta version ${{ needs.get_version.outputs.version }}" \
            --body "### Pull request created by [PicGuard-WinGet-Updater](https://github.com/${{ github.repository }}) workflow run [#${{ github.run_number }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }})"
